### ISSUE TITLE
Error when compiling

### ISSUE THREAD

**Issue by RobinPetit** [AntoinePassemiers/Recursive-Least-Squares-Algorithm-With-Kafka-And-Spark#1]
I unfortunately am not able to compile the code, I have the following error: 
```
$ make
make: *** No targets specified and no makefile found.  Stop.
```

Please help

**Comment by AntoinePassemiers** [comment]
I will provide a Makefile soon. If you are working on Windows you will have to add the -fPIC flag to it in order to compile the notebooks. I never tested it though.

**Comment by RobinPetit** [comment]
I am on Win XP SP3

**Comment by TheoVerhelst** [comment]
Same here on my Atari 520ST, pls fix it. This project is a dependency for a NodeJS package I need.

**Comment by TheoVerhelst** [comment]
I tried cloning the repo, but git says
```
error: independent ethics committee did not approve your request for cloning,
please find an alternative experimental protocol. See the logs for details.
```

**Comment by RobinPetit** [comment]
I downgraded gcc to version 2.7.2.3, and it does compile now. Closing the issue.
